2022-07-27 22:54:56,464 INFO    MainThread:25884 [wandb_setup.py:_flush():76] Configure stats pid to 25884
2022-07-27 22:54:56,464 INFO    MainThread:25884 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2022-07-27 22:54:56,465 INFO    MainThread:25884 [wandb_setup.py:_flush():76] Loading settings from /workspace/youtube-humpback-whale-classifier/classification/wandb/settings
2022-07-27 22:54:56,465 INFO    MainThread:25884 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2022-07-27 22:54:56,465 INFO    MainThread:25884 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-07-27 22:54:56,465 INFO    MainThread:25884 [wandb_init.py:_log_setup():461] Logging user logs to /workspace/youtube-humpback-whale-classifier/classification/wandb/run-20220727_225456-4e0hfcto/logs/debug.log
2022-07-27 22:54:56,465 INFO    MainThread:25884 [wandb_init.py:_log_setup():462] Logging internal logs to /workspace/youtube-humpback-whale-classifier/classification/wandb/run-20220727_225456-4e0hfcto/logs/debug-internal.log
2022-07-27 22:54:56,465 INFO    MainThread:25884 [wandb_init.py:init():495] calling init triggers
2022-07-27 22:54:56,465 INFO    MainThread:25884 [wandb_init.py:init():498] wandb.init called with sweep_config: {}
config: {}
2022-07-27 22:54:56,465 INFO    MainThread:25884 [wandb_init.py:init():514] re-initializing run, found existing run on stack: pygsrcpy
2022-07-27 22:54:56,482 ERROR   MainThread:25884 [wandb_init.py:init():1070] error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/wandb_init.py", line 1043, in init
    run = wi.init()
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/wandb_init.py", line 527, in init
    self._wl._global_run_stack[-1].finish()
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/wandb_run.py", line 256, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/wandb_run.py", line 222, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/wandb_run.py", line 1673, in finish
    return self._finish(exit_code, quiet)
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/wandb_run.py", line 1679, in _finish
    tel.feature.finish = True
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/lib/telemetry.py", line 41, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/wandb_run.py", line 572, in _telemetry_callback
    self._telemetry_flush()
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/wandb_run.py", line 583, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/interface/interface_shared.py", line 74, in _publish_telemetry
    self._publish(rec)
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/interface/interface_queue.py", line 49, in _publish
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
2022-07-27 22:54:59,776 INFO    MainThread:25884 [wandb_init.py:_pause_backend():374] pausing backend
2022-07-27 22:54:59,776 INFO    MainThread:25884 [jupyter.py:save_ipynb():377] not saving jupyter notebook
2022-07-27 22:55:09,543 INFO    MainThread:25884 [wandb_init.py:_resume_backend():383] resuming backend
2022-07-27 22:55:09,771 INFO    MainThread:25884 [wandb_init.py:_pause_backend():374] pausing backend
2022-07-27 22:55:09,771 INFO    MainThread:25884 [jupyter.py:save_ipynb():377] not saving jupyter notebook
2022-07-27 22:55:17,537 INFO    MainThread:25884 [wandb_init.py:_resume_backend():383] resuming backend
2022-07-27 22:55:17,597 INFO    MainThread:25884 [wandb_init.py:_pause_backend():374] pausing backend
2022-07-27 22:55:17,597 INFO    MainThread:25884 [jupyter.py:save_ipynb():377] not saving jupyter notebook
2022-07-27 22:55:40,073 INFO    MainThread:25884 [wandb_init.py:_resume_backend():383] resuming backend
2022-07-27 22:55:40,132 INFO    MainThread:25884 [wandb_init.py:_pause_backend():374] pausing backend
2022-07-27 22:55:40,132 INFO    MainThread:25884 [jupyter.py:save_ipynb():377] not saving jupyter notebook
2022-07-27 22:55:49,031 INFO    MainThread:25884 [wandb_init.py:_resume_backend():383] resuming backend
2022-07-27 22:55:49,220 INFO    MainThread:25884 [wandb_init.py:_pause_backend():374] pausing backend
2022-07-27 22:55:49,220 INFO    MainThread:25884 [jupyter.py:save_ipynb():377] not saving jupyter notebook
2022-07-27 22:55:51,050 INFO    MainThread:25884 [wandb_init.py:_resume_backend():383] resuming backend
2022-07-27 22:55:51,239 INFO    MainThread:25884 [wandb_init.py:_pause_backend():374] pausing backend
2022-07-27 22:55:51,240 INFO    MainThread:25884 [jupyter.py:save_ipynb():377] not saving jupyter notebook
2022-07-27 22:55:53,135 INFO    MainThread:25884 [wandb_init.py:_resume_backend():383] resuming backend
2022-07-27 22:55:53,322 INFO    MainThread:25884 [wandb_init.py:_pause_backend():374] pausing backend
2022-07-27 22:55:53,322 INFO    MainThread:25884 [jupyter.py:save_ipynb():377] not saving jupyter notebook
2022-07-27 22:55:56,681 INFO    MainThread:25884 [wandb_init.py:_resume_backend():383] resuming backend
2022-07-27 22:55:56,739 INFO    MainThread:25884 [wandb_init.py:_pause_backend():374] pausing backend
2022-07-27 22:55:56,740 INFO    MainThread:25884 [jupyter.py:save_ipynb():377] not saving jupyter notebook
2022-07-27 22:56:01,452 INFO    MainThread:25884 [wandb_init.py:_resume_backend():383] resuming backend
2022-07-27 22:56:01,511 INFO    MainThread:25884 [wandb_init.py:_pause_backend():374] pausing backend
2022-07-27 22:56:01,511 INFO    MainThread:25884 [jupyter.py:save_ipynb():377] not saving jupyter notebook
2022-07-27 22:56:27,868 INFO    MainThread:25884 [wandb_init.py:_resume_backend():383] resuming backend
